services:
  - docker:dind

build-only:
  stage: build
  image: docker:latest
  script:
    - 'docker build --pull --no-cache --rm --file Dockerfile .'
  except:
    - tags

build-delivery:
  stage: build
  image: docker:latest
  variables:
    PROJECT_NAME: docker_buildx
    RELEASE_TAG: ${PROJECT_NAME}_${CI_COMMIT_REF_NAME}
    RELEASE_TAG_LATEST: ${PROJECT_NAME}_latest
  script:
    - 'echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin'
    - 'docker build --pull --no-cache --rm --tag "${DOCKER_REPOSITORY}:${RELEASE_TAG}_local" --file Dockerfile .'
    - 'PLATFORM=$(docker image inspect "${DOCKER_REPOSITORY}:${RELEASE_TAG}_local" --format "{{.Os}}_{{.Architecture}}{{if .Variant}}_{{.Variant}}{{end}}")'
    - 'docker image tag "${DOCKER_REPOSITORY}:${RELEASE_TAG}_local" "${DOCKER_REPOSITORY}:${RELEASE_TAG}_${PLATFORM}"'
    - 'docker push "${DOCKER_REPOSITORY}:${RELEASE_TAG}_${PLATFORM}"'
    - 'docker manifest create "${DOCKER_REPOSITORY}:${RELEASE_TAG}" --amend "${DOCKER_REPOSITORY}:${RELEASE_TAG}_linux_amd64" --amend "${DOCKER_REPOSITORY}:${RELEASE_TAG}_linux_arm64_v8"'
    - 'docker manifest push "${DOCKER_REPOSITORY}:${RELEASE_TAG}"'
  only:
    - tags
